name: Release Spoon
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zip Spoon Directory
        uses: thedoctor0/zip-release@master
        with:
          directory: source
          filename: WindowManager.spoon.zip
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Spoon
        uses: ncipollo/release-action@v1
        with:
          artifacts: WindowManager.spoon.zip
          body: ${{ steps.tag_version.outputs.changelog }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
